# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm/pnpm
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      all-dependencies:
        update-types:
          - 'major'
          - 'minor'
          - 'patch'
    # Open PRs for grouped updates
    open-pull-requests-limit: 10
    # Commit message
    commit-message:
      prefix: 'chore'
      prefix-development: 'chore'
      include: 'scope'
